# Generated by Django 5.2.7 on 2025-10-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='salt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='noteversion',
            name='salt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
