# Generated by Django 5.2.7 on 2025-10-24 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_options_folder_note_folder_sharedfolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('markdown', 'Markdown Note'), ('canvas', 'Canvas Note')], default='markdown', max_length=20),
        ),
        migrations.AddField(
            model_name='sharednote',
            name='note_type',
            field=models.CharField(choices=[('markdown', 'Markdown Note'), ('canvas', 'Canvas Note')], default='markdown', max_length=20),
        ),
        migrations.CreateModel(
            name='CanvasElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('textbox', 'Text Box'), ('image', 'Image')], max_length=20)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=200)),
                ('height', models.IntegerField(default=100)),
                ('text_content', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='canvas_images/')),
                ('z_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_elements', to='notes.note')),
                ('shared_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_elements', to='notes.sharednote')),
            ],
            options={
                'ordering': ['z_index', 'created_at'],
            },
        ),
    ]
