# Generated by Django 5.2.7 on 2025-10-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_note_type_sharednote_note_type_canvaselement'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvaselement',
            name='fill_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='canvaselement',
            name='path_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='canvaselement',
            name='stroke_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='canvaselement',
            name='stroke_width',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='canvaselement',
            name='element_type',
            field=models.CharField(choices=[('textbox', 'Text Box'), ('image', 'Image'), ('rectangle', 'Rectangle'), ('circle', 'Circle'), ('line', 'Line'), ('freehand', 'Freehand Drawing')], max_length=20),
        ),
    ]
