# Generated by Django 5.2.7 on 2025-10-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_canvaselement_fill_color_canvaselement_path_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvaselement',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canvaselement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
